### ISSUE TITLE
Unable to connect via BuddyPress

### ISSUE THREAD

**Issue by robinschuster** [eduardoweiland/buddypress-xmlrpc-receiver#5]
Hello,

i am comissioned by setting up a buddypress-instance so it can be connectet to via the BuddyDroid app referenced in this repo's README file. Because the original xmlrpc-plugin recommended from the app seems to be no longer actively maintained, i chose this plugin over it. I followed the installation steps and the installation was successful. BuddyPress and buddypress-xmlrpc-reciever are installed and activated, so the current setup is now:
##### Server:

Wordpress `v4.3.1`
Buddypress `v2.3.3`
buddypress-xmlrpc-reciever 43bb52d6525e4fcd942e098e4e8bebdcbef3de7b
##### Client

BuddyDroid `v3.1`

The Problem is that i am unable to connect to the BuddyPress instance via the app. As soon as i submit correct login userdata, the app seems to get a bad response and outputs `org.xmlrpc.android.XMLRPCException: HTTP status code: 500 was returned. Internal Server Error.` as a toast message.
For comparison: With wrong userdata, the app outputs `org.xmlrpc.android.XMLRPCFault: XMLRPC Fault: Incorrect username or password. [code 403]`, which indicates that the interface is partially behaving correctly.

**Comment by ubuntume** [comment]
did you ever get this issue resolved

**Comment by elblogbruno** [comment]
Did someone fix the problem?

**Comment by ubuntume** [comment]
I was able to get it working. You will need to comment out some lines of code. Check the github ubuntume

**Comment by elblogbruno** [comment]
You modified and posted it?
You are god and make my day
Thanks a lot

**Comment by ubuntume** [comment]
https://github.com/ubuntume/buddydroid

**Comment by elblogbruno** [comment]
Sorry to ask a lot but i've tried to built the app in android studio and gives me more than 100 errors
Any solution

**Comment by eduardoweiland** [comment]
This project is no longer supported by me. I have added a notice on the README linking to @ubuntume's fork.

**Comment by ubuntume** [comment]
Try an older version from around early 200s

**Comment by elblogbruno** [comment]
Which one?

**Comment by elblogbruno** [comment]
Why you close it?

--
Enviado desde la aplicación myMail para Android

sábado, 23 septiembre 2017, 11:28p. m. +02:00 de Eduardo Weiland notifications@github.com<mailto:notifications@github.com>:


Closed #5<https://github.com/eduardoweiland/buddypress-xmlrpc-receiver/issues/5>.
